### ISSUE TITLE
a minor typo

### ISSUE THREAD

**Issue by lywcn** [eayvali/Computing-Motion-Derivatives-from-6DoF-Noisy-Pose-Measurements#1]
Hi, Elif

Thank you so much for your great work on this! Your derivation summary is so inspiring for my research!

I just want to let you know that there is a typo in the table for the "Body Derivatives" section. The last row for $^BW_q(^Sq)$ should be "-q_3 q_2 -q_1 q_0". Basically, $q_1$ should have a negative sign.

Thank you!
John

**Comment by eayvali** [comment]
Hi John,
Good catch! The code is correct. I'll fix the typo in the ReadMe.
Glad to hear you find it useful.

**Comment by lywcn** [comment]
Thank you very much!
